[pytest]
# Especifica el módulo de configuración de Django que debe usar pytest
DJANGO_SETTINGS_MODULE = config.settings
# Define los patrones de nombres de archivos que se considerarán pruebas
python_files = tests.py test_*.py *_tests.py
# Añade el directorio 'src' al path de Python para la resolución de módulos
pythonpath = src
