# Generated by Django 5.2.12 on 2026-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_role_userrole_customuser_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                ("configuracion", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "centro",
                "verbose_name_plural": "centros",
                "db_table": "centros",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="centros",
            field=models.ManyToManyField(
                db_table="profesores_sedes", related_name="usuarios", to="users.centro"
            ),
        ),
    ]
