# Generated by Django 5.2.12 on 2026-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_centro_customuser_centros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(db_column="password_hash", max_length=255),
        ),
    ]
