# Generated by Django 5.2.12 on 2026-03-17 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_centro_customuser_centros"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "módulo",
                "verbose_name_plural": "módulos",
                "db_table": "modulos",
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("curso_academico_id", models.IntegerField()),
                (
                    "centro",
                    models.ForeignKey(
                        db_column="centro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.centro",
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo",
                "verbose_name_plural": "grupos",
                "db_table": "grupos",
            },
        ),
    ]
